# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/oled_switches_const.xdc

# Block Designs: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/oled_switches_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_switches_design || ORIG_REF_NAME==oled_switches_design} -quiet] -quiet

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_processing_system7_0_0/oled_switches_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_switches_design_processing_system7_0_0 || ORIG_REF_NAME==oled_switches_design_processing_system7_0_0} -quiet] -quiet

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_PmodGPIO_0_0/oled_switches_design_PmodGPIO_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_switches_design_PmodGPIO_0_0 || ORIG_REF_NAME==oled_switches_design_PmodGPIO_0_0} -quiet] -quiet

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_PmodGPIO_1_0/oled_switches_design_PmodGPIO_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_switches_design_PmodGPIO_1_0 || ORIG_REF_NAME==oled_switches_design_PmodGPIO_1_0} -quiet] -quiet

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_xbar_0/oled_switches_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_switches_design_xbar_0 || ORIG_REF_NAME==oled_switches_design_xbar_0} -quiet] -quiet

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_ps7_0_axi_periph_0/oled_switches_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_switches_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==oled_switches_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_rst_ps7_0_50M_0/oled_switches_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_switches_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==oled_switches_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_PmodOLED_0_0/oled_switches_design_PmodOLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_switches_design_PmodOLED_0_0 || ORIG_REF_NAME==oled_switches_design_PmodOLED_0_0} -quiet] -quiet

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_auto_pc_0/oled_switches_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==oled_switches_design_auto_pc_0 || ORIG_REF_NAME==oled_switches_design_auto_pc_0} -quiet] -quiet

# XDC: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/oled_switches_design_ooc.xdc
