# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_processing_system7_0_0/oled_switches_design_processing_system7_0_0.xci
# IP: The module: 'oled_switches_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_processing_system7_0_0/oled_switches_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'oled_switches_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_processing_system7_0_0/oled_switches_design_processing_system7_0_0.xci
# IP: The module: 'oled_switches_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jeffb/Vivado_Projects/ECE520_Final_Projects/oled_switches/hardware/bd/oled_switches_design/ip/oled_switches_design_processing_system7_0_0/oled_switches_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'oled_switches_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
